services:
  # Backend API
  - type: web
    name: farm-machinery-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_CSE_KEY
        sync: false
      - key: GOOGLE_CSE_CX
        sync: false

  # Frontend (Static Site)
  - type: web
    name: farm-machinery-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
